# Site settings
# These are used to personalize your new site.
title: Nathan Dykema # your name here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Technology in Computer-Science (class of 2026)
  <br /><br />
  <a href="https://example.com/resume">View My Resume</a>
  <br /><br />
  <a href="www.linkedin.com/in/nathan-dykema-b089aa1bb/">View My LinkedIn Profile</a>
repository: "ndykema/ndykema.github.io"
github_username:  ndykema # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

